# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread',
            new_name='Forum',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='thread',
            new_name='threads',
        ),
    ]
