# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
