# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(default='', max_length=35),
        ),
    ]
