# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171206_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Hats', 'Hats')], default='', max_length=35),
        ),
    ]
