# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171209_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Hats', 'Hats'), ('Accessories', 'Accessories'), ('Coats', 'Coats'), ('Trousers', 'Trousers'), ('Suits', 'Suits'), ('Dresses', 'Dresses'), ('Shirts', 'Shirts'), ('t-shirts', 't-shirts')], default='', max_length=35),
        ),
    ]
