# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171209_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=35),
        ),
    ]
