# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_long_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_short_description',
            field=models.TextField(default=''),
        ),
    ]
