# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171209_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Shoes', 'Shoes'), ('Hoodies', 'Hoodies'), ('Hats', 'Hats'), ('Coats', 'Coats'), ('Trousers', 'Trousers'), ('Suits', 'Suits'), ('Dresses', 'Dresses'), ('Shirts', 'Shirts'), ('t-shirts', 't-shirts'), ('Knitwear', 'Knitwear')], default='', max_length=35),
        ),
    ]
